import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0b1020",
  },
  content: {
    paddingHorizontal: 18,
    paddingBottom: 30,
    paddingTop: 12,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  eyebrow: {
    color: "#93c5fd",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  title: {
    color: "#f8fafc",
    fontSize: 30,
    fontWeight: "800",
  },
  subtitle: {
    color: "#cbd5e1",
    fontSize: 14,
    marginTop: 2,
  },
  logoutButton: {
    backgroundColor: "#111827",
    borderColor: "#334155",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  logoutText: {
    color: "#f8fafc",
    fontWeight: "700",
  },
  heroCard: {
    alignItems: "center",
    backgroundColor: "linear-gradient(135deg, #1d4ed8 0%, #0ea5e9 100%)",
    borderRadius: 22,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
    overflow: "hidden",
    padding: 20,
  },
  heroLabel: {
    color: "#dbeafe",
    fontSize: 13,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  heroValue: {
    color: "#ffffff",
    fontSize: 34,
    fontWeight: "800",
  },
  heroTrend: {
    color: "#dbeafe",
    fontSize: 13,
    marginTop: 6,
  },
  heroBadge: {
    alignItems: "center",
    backgroundColor: "#facc15",
    borderRadius: 16,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  metricCard: {
    backgroundColor: "#111827",
    borderColor: "#1f2937",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    padding: 14,
    width: "48%",
  },
  metricIcon: {
    alignItems: "center",
    borderRadius: 10,
    height: 40,
    justifyContent: "center",
    marginBottom: 12,
    width: 40,
  },
  metricLabel: {
    color: "#94a3b8",
    fontSize: 12,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  metricValue: {
    color: "#f8fafc",
    fontSize: 24,
    fontWeight: "800",
  },
  metricChange: {
    fontSize: 12,
    fontWeight: "700",
    marginTop: 6,
  },
  sectionHeader: {
    marginBottom: 10,
  },
  sectionTitle: {
    color: "#f8fafc",
    fontSize: 20,
    fontWeight: "700",
  },
  quickActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 18,
  },
  actionButton: {
    alignItems: "center",
    backgroundColor: "#111827",
    borderColor: "#1f2937",
    borderRadius: 14,
    borderWidth: 1,
    flexBasis: "22%",
    justifyContent: "center",
    minHeight: 78,
    padding: 12,
  },
  actionText: {
    color: "#e2e8f0",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 8,
    textAlign: "center",
  },
  panel: {
    backgroundColor: "#111827",
    borderColor: "#1f2937",
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
  },
  activityRow: {
    alignItems: "center",
    borderBottomColor: "#1f2937",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingVertical: 12,
  },
  dot: {
    backgroundColor: "#60a5fa",
    borderRadius: 999,
    height: 10,
    marginRight: 12,
    width: 10,
  },
  activityTextWrap: {
    flex: 1,
  },
  activityTitle: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "700",
  },
  activityDetail: {
    color: "#94a3b8",
    fontSize: 12,
    marginTop: 3,
  },
  activityTime: {
    color: "#93c5fd",
    fontSize: 12,
    fontWeight: "700",
  },
});
