import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#050816",
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  title: {
    color: "#F8FAFC",
    fontSize: 28,
    fontWeight: "800",
  },
  logoutButton: {
    backgroundColor: "#081426",
    borderColor: "#1A304A",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  logoutText: {
    color: "#E6F7FF",
    fontWeight: "600",
  },
  userLabel: {
    color: "#CBD5E1",
    marginBottom: 12,
  },
  cacheBanner: {
    alignItems: "center",
    backgroundColor: "#7C2D12",
    borderColor: "#FFA500",
    borderLeftWidth: 4,
    borderRadius: 10,
    flexDirection: "row",
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  cacheText: {
    color: "#FBBF24",
    fontWeight: "700",
    fontSize: 14,
  },
  cacheSubtext: {
    color: "#FED7AA",
    fontSize: 12,
    marginTop: 2,
  },
  searchInput: {
    backgroundColor: "#07111F",
    borderColor: "#1A304A",
    borderRadius: 13,
    borderWidth: 1,
    color: "#E6F7FF",
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  error: {
    color: "#fca5a5",
    marginBottom: 8,
  },
  listContent: {
    paddingBottom: 80,
  },
  card: {
    backgroundColor: "#091222",
    borderColor: "#162B46",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: 12,
    padding: 12,
  },
  cardRestricted: {
    borderColor: "rgba(239, 68, 68, 0.7)",
    borderWidth: 1,
  },
  avatar: {
    backgroundColor: "#081426",
    borderRadius: 26,
    height: 52,
    width: 52,
  },
  avatarPlaceholder: {
    alignItems: "center",
    backgroundColor: "#00D9FF",
    borderRadius: 26,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  avatarPlaceholderText: {
    color: "#001018",
    fontSize: 20,
    fontWeight: "700",
  },
  userMeta: {
    flex: 1,
    marginLeft: 12,
  },
  name: {
    color: "#F8FAFC",
    fontSize: 18,
    fontWeight: "700",
  },
  email: {
    color: "#B6F3FF",
    marginTop: 4,
  },
  phone: {
    color: "#CBD5E1",
    marginTop: 2,
  },
  location: {
    color: "#00CFFF",
    marginTop: 6,
  },
  loader: {
    marginTop: 40,
  },
  footerLoader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    paddingVertical: 32,
  },
  footerLoaderText: {
    color: "#00CFFF",
    fontSize: 14,
    marginLeft: 12,
  },
  modalOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.72)",
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#091222",
    borderColor: "#162B46",
    borderRadius: 20,
    borderWidth: 1,
    padding: 20,
    width: "100%",
  },
  modalCardRestricted: {
    borderColor: "rgba(239, 68, 68, 0.7)",
    borderWidth: 1,
  },
  modalTitle: {
    color: "#F8FAFC",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 18,
    textAlign: "center",
  },
  modalSubtitle: {
    color: "#CBD5E1",
    fontSize: 16,
    marginBottom: 16,
    textAlign: "center",
  },
  modalAvatar: {
    alignSelf: "center",
    backgroundColor: "#081426",
    borderRadius: 48,
    height: 96,
    marginBottom: 10,
    width: 96,
  },
  primaryAction: {
    alignItems: "center",
    backgroundColor: "#00D9FF",
    borderRadius: 13,
    marginBottom: 12,
    padding: 14,
  },
  secondaryAction: {
    alignItems: "center",
    backgroundColor: "#081426",
    borderColor: "#1A304A",
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 12,
    padding: 14,
  },
  cancelAction: {
    alignItems: "center",
    borderColor: "#334155",
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
  },
  actionText: {
    color: "#001018",
    fontSize: 15,
    fontWeight: "700",
  },
  cancelText: {
    color: "#CBD5E1",
    fontSize: 14,
    fontWeight: "600",
  },
  scrollToTopButton: {
    alignItems: "center",
    backgroundColor: "#00D9FF",
    borderRadius: 50,
    bottom: 20,
    height: 56,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    width: 56,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
});
